# =============================================================================
# GIT OPERATIONS COMPOSITE ACTION
# =============================================================================
# This action provides standardized Git operations for CI/CD pipelines including
# tagging, committing, pushing, and branch management.
#
# USAGE:
#   - name: '🏷️ Git Operations'
#     uses: ./.github/actions/git-operations
#     with:
#       operation: 'tag-and-push'
#       tag-name: 'v1.2.3'
#       commit-message: 'Release 1.2.3'
#       push-changes: true
#       force-push: false
#
# INPUTS:
#   - operation: Git operation to perform (tag, commit, push, tag-and-push, all)
#   - tag-name: Git tag name (for tag operations)
#   - tag-message: Message for the tag
#   - commit-message: Message for the commit
#   - push-changes: Whether to push changes
#   - force-push: Whether to force push (use with caution)
#   - branch: Target branch for operations
#   - user-name: Git user name
#   - user-email: Git user email
#   - add-pattern: File pattern to add (default: all)
#   - create-branch: Whether to create branch if it doesn't exist
#   - checkout-branch: Whether to checkout the target branch
#   - fetch-depth: Git fetch depth (0 for full history)
#
# OUTPUTS:
#   - tag-created: Whether tag was created
#   - commit-created: Whether commit was created
#   - changes-pushed: Whether changes were pushed
#   - branch-name: Current branch name
#   - last-commit: Last commit hash
#   - last-tag: Last tag name
# =============================================================================

name: 'Git Operations'
description: 'Handles Git operations like committing and pushing changes'

inputs:
  commit-message:
    description: 'Commit message to use'
    required: true
    default: 'chore: update versions'
  branch:
    description: 'Branch to push to'
    required: true
    default: 'develop'
  maven-version:
    description: 'Maven version for commit message'
    required: false
    default: ''
  npm-version:
    description: 'NPM version for commit message'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: '📝 Configure Git'
      shell: bash
      run: |
        echo "📝 Configuring Git..."
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "✅ Git configured"

    - name: '📝 Commit Changes'
      shell: bash
      run: |
        echo "📝 Committing changes..."
        
        # Add all changes
        git add -A
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          # Create enhanced commit message
          COMMIT_MSG="${{ inputs.commit-message }}"
          
          if [ -n "${{ inputs.maven-version }}" ]; then
            COMMIT_MSG="$COMMIT_MSG [Maven: ${{ inputs.maven-version }}]"
          fi
          
          if [ -n "${{ inputs.npm-version }}" ]; then
            COMMIT_MSG="$COMMIT_MSG [NPM: ${{ inputs.npm-version }}]"
          fi
          
          # Commit changes
          git commit -m "$COMMIT_MSG"
          echo "✅ Changes committed: $COMMIT_MSG"
        fi

    - name: '📝 Push to Branch'
      shell: bash
      run: |
        echo "📝 Pushing to ${{ inputs.branch }} branch..."
        
        # Check if we're on the target branch
        CURRENT_BRANCH=$(git branch --show-current)
        git push origin ${{ inputs.branch }}
        echo "✅ Changes pushed to ${{ inputs.branch }} branch"
