name: 'Test Without Validation'

on:
  workflow_call:
    inputs:
      project-type:
        description: 'Type of project (maven, npm, or hybrid)'
        required: true
        type: string
        default: 'hybrid'
      java-version:
        description: 'Java version to use'
        required: false
        type: string
        default: '17'
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '18'
      maven-working-directory:
        description: 'Working directory for Maven project'
        required: false
        type: string
        default: '.'
      npm-working-directory:
        description: 'Working directory for NPM project'
        required: false
        type: string
        default: '.'
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  test:
    name: 'Test Without Validation'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Display info'
        run: |
          echo "Project type: ${{ inputs.project-type }}"
          echo "Java version: ${{ inputs.java-version }}"
          echo "Node version: ${{ inputs.node-version }}"
          echo "Maven working directory: ${{ inputs.maven-working-directory }}"
          echo "NPM working directory: ${{ inputs.npm-working-directory }}"
          echo "✅ Test workflow without validation works!"
