name: 'Minimal Test Workflow'

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to display'
        required: false
        type: string
        default: 'Hello World'
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  test:
    name: 'Minimal Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Display message'
        run: echo "${{ inputs.message }}"

      - name: 'List files'
        run: ls -la
